# Site settings
title: Josh Jamieson
email: joshjamieson16@gmail.com
url: staticky1.github.io
description: "A collection of interesting projects and articles from my experience programming and working on technical art within C++ and the Unreal Engine."
keywords: "Portfolio, unreal engine, art, programming"
skills: "Programming - Technical Art - Unreal Generalist"
meta_author: Jamieson Josh

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4f5d75 #80B3FF
  primary-rgb: "79, 93, 117" #"128,179,255"
  secondary: 2d3142 #FD6E8A
  secondary-dark: bfc0c0 #A2122F

# Footer settings
footer:
  copyright: Josh Jamieson
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/josh-jamieson-law/
  - title: github
    url: http://github.com/staticky1
  - title: discord
    url: https://discord.com/users/203744315799764993

# Postal address (add as many lines as necessary)
address:
  - line: Cass Bay,
  - line: Christchurch,
  - line: New Zealand

# Credits content
credits: 'To make this site I''ve edited the open source Freelancer theme, which itself is based on the Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
